############
#####
###

# enable section is for your choice if you want to play sound to an certain event or not
# sound section, choose any sound you want
# List of possible sounds https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
# volume section, change volume to your desire
# pitch section, change pitch to your desire

# OpenInventory event
OpenInventory:
   enable: true
   sound: 'ENTITY_CHICKEN_EGG'
   volume: 1.0
   pitch: 1.0

CloseInventory:
   enable: true
   sound: 'ENTITY_CHICKEN_EGG'
   volume: 1.0
   pitch: 1.0

BlockBreak:
   enable: true
   sound: 'ENTITY_CHICKEN_EGG'
   volume: 1.0
   pitch: 1.0

BlockPlace:
   enable: true
   sound: 'ENTITY_CHICKEN_EGG'
   volume: 1.0
   pitch: 1.0

DropItem:
   enable: true
   sound: 'ENTITY_CHICKEN_EGG'
   volume: 1.0
   pitch: 1.0

PickupItem:
   enable: true
   sound: 'ENTITY_CHICKEN_EGG'
   volume: 1.0
   pitch: 1.0

WorldChange:
   enable: false
   sound: 'ENTITY_CHICKEN_EGG'
   volume: 1.0
   pitch: 1.0

PlayerMove:
   enable: false
   sound: 'ENTITY_CHICKEN_EGG'
   volume: 1.0
   pitch: 1.0

PlayerJoin:
   enable: false
   sound: 'ENTITY_CHICKEN_EGG'
   volume: 1.0
   pitch: 1.0

PlayerLeave:
   enable: false
   sound: 'ENTITY_CHICKEN_EGG'
   volume: 1.0
   pitch: 1.0

InventoryClick:
   enable: false
   sound: 'ENTITY_CHICKEN_EGG'
   volume: 1.0
   pitch: 1.0

PlayerHit:
   enable: false
   sound: 'ENTITY_CHICKEN_EGG'
   volume: 1.0
   pitch: 1.0

EntityHit:
   enable: false
   sound: 'ENTITY_CHICKEN_EGG'
   volume: 1.0
   pitch: 1.0

CommandUse:
   enable: true
   sound: 'ENTITY_CHICKEN_EGG'
   volume: 1.0
   pitch: 1.0

UnknownCommandUse:
   enable: false
   sound: 'ENTITY_CHICKEN_EGG'
   volume: 1.0
   pitch: 1.0

# These will only check the not permitted access on using sounds
NoPermission:
   enable: true
   sound: 'ENTITY_CHICKEN_EGG'
   volume: 1.0
   pitch: 1.0